### ISSUE TITLE
Would be nice if you can add small architectural digram and steps to run the code

### ISSUE THREAD

**Issue by javaHelper** [Nabeel110/Springboot-Event-Driven-Microservices-with-kafka#1]

**Comment by Nabeel110** [comment]
Hey, 
Thanks for reaching out. I just got done with this yesterday.
I'll be adding an architecture diagram with steps to run the code. It's a work in progress

**Comment by Nabeel110** [comment]
Documentation has been added. Hence I am closing the issue.
